name: pushworld_bot
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - ipykernel
  - gymnasium
  - pybind11
  - igraph
  - python-igraph>=0.11
  - llvm-openmp>=19
  - cairo>=1.18
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pip
  - pip:
      - texttable==1.7.0
