summary: "Need to try the simple room with the VQ to add goal region detection"

puzzle: "manual/simple"
n_obs: 20
encoder: "VectorQuantizer"
clones_per_obs: 20
seq_len: 100

training_procedure:
  n_iters_cscg: 100

environment_reset:
  method: null
  mean: 6
  variance: 0

wandb:
  project: "cscg-pushworld"
  entity: "jacobgroner-cornell-university"
