summary: "Debug new training procedure"

puzzle: "manual/corridor6x1"
n_obs: 4
encoder: "VectorQuantizer"
clones_per_obs: 2
seq_len: 1000

training_procedure:
  n_iters_cscg: 100

environment_reset:
  method: null
  mean: 6
  variance: 0

wandb:
  project: "cscg-pushworld"
  entity: "jacob-simon"
