puzzle:
  default: "manual/actor_only"
  description: "Which puzzle to run. All puzzles should be placed in benchmark/puzzles, and this field should include the subdirectory and the puzzle name."

encoder:
  default: "IntEncoder"
  description: "An nn.Module for mapping an input to an observation. See encoders.py for list of options."

n_obs: 
  default: 10
  description: "The number of observations. The encoder maps an input to an observation and the cscg takes in a sequence of observations and predicts which latent clone of the observation the agent is in."

clones_per_obs:
  default: 1
  description: "The number of latent states the cscg assigns to each observation."

seq_len:
  default: 10
  description: "The number of actions to take in the environment. Each action steps the environment once and adds another data point."

seed:
  default: 49
  description: "Seed for all random procecess to make experiments replicable"