[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pushworld"
version = "0.1.0"
description = "PushWorld package (local editable install)"
readme = ""
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
